### ISSUE TITLE
tog4in1 crashes if video has chapters and the first chapter's time is > 0

### ISSUE THREAD

**Issue by herbrot** [zTnR/mpv-osc-tog4in1#1]
chapter-make-read.lua - chapters.chp:
00:00:01.000 Intro
00:05:30.000 I. Meeting

mpv:
mpv v0.39.0-430-ga283f66e Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 30 2024 00:11:36

[tog4in1]
[tog4in1] stack traceback:
[tog4in1]       .../mpv/portable_config/scripts/tog4in1.lua:1562: in function 'render_elements'
[tog4in1]       .../mpv/portable_config/scripts/tog4in1.lua:3633: in function 'render'
[tog4in1]       .../mpv/portable_config/scripts/tog4in1.lua:3762: in function 'cb'
[tog4in1]       mp.defaults:370: in function 'process_timers'
[tog4in1]       mp.defaults:543: in function 'dispatch_events'
[tog4in1]       mp.defaults:516: in function <mp.defaults:515>
[tog4in1]       [C]: at 0x7ff63b30de70
[tog4in1]       [C]: at 0x7ff63b30cc90
**[tog4in1] Lua error: .../mpv/portable_config/scripts/tog4in1.lua:2880: attempt to index local 'file' (a nil value)**

This happens when I start the mpv and move mouse to 'prev chapter' button

**Comment by zTnR** [comment]
Now that's some chapterism fanciness. Should be "fixed".

**Comment by zTnR** [comment]
Ah yes, didn't think about that.
Thanks for the feedback
